import { AdvancedImage } from "@cloudinary/react";
import { Cloudinary } from "@cloudinary/url-gen";
import { Transformation } from "@cloudinary/url-gen";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { GetServerSideProps } from "next";

const inter = Inter({ subsets: ["latin"] });

type Pictures = any;

export default function Home({ images }: Pictures) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1>Test</h1>
        <pre>{JSON.stringify(images, null, 2)}</pre>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  // Fetch data from external API
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/images`);
  const images = await res.json();

  // Pass folders to the page via props
  return { props: { images } };
};
